config/routes.rb
Rails.application.routes.draw do

resources :carts, only:[:create, :show]
resources :items, only: [:show, :index]
  root 'items#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_cart_items
  has_many :items, through: :join_cart_items
end

app/models/item.rb
class Item < ApplicationRecord
	validates :title, presence: true, length: { in: 2..10 }
	validates :description, presence: true, length: { in: 2..200 }
	validates :price, presence: true
	URL_REGEXP = /\A^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$\z/ix
	validates :image_url, presence: true, format: { with: URL_REGEXP, message: 'You provided invalid URL'}



	has_many :join_order_items
	has_many :orders, through: :join_order_items

  has_many :join_cart_items
  has_many :carts, through: :join_cart_items
end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_order_item.rb
class JoinOrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :join_order_items
	has_many :items, through: :join_order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_one :cart

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:is_alive, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:is_alive, :email, :password, :password_confirmation, :current_password)}
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    @u=current_user.id
    @i=session[:item_id]


    if current_user.cart == nil
      @cart = Cart.create(user_id: @u)
    end

    @cart = JoinCartItem.create(cart_id:current_user.cart.id, item_id: @i)

     if @cart.save
       redirect_to '/'
     else
     puts "Try again"
     end
 end


 def show
   @cart = Cart.find(params[:id])
   @tab=@cart.items
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
    @items  = Item.all
    end
    def show

    	@item = Item.find(params[:id])
			session[:item_id]=params[:id]

    end
end

app/controllers/joincartitems_controller.rb
class JoincartitemsController < ApplicationController

  def create
    @u=current_user.id
    @i=session[:item_id]


    @cart = JoinCartItem.create(cart_id: @u, item_id: @i)
     if @cart.save
       redirect_to '/'
     else
     puts "Try again"
     end
  end
  def show


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/joincartitems_helper.rb
module JoincartitemsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/show.html.erb
<h1>Voici les articles dans ton panier:</h1>

<table class="table">
 <thead class="thead-dark">
   <tr>
     <th scope="col">Produits</th>
     <th scope="col">Prix</th>
   </tr>
 </thead>
 <tbody>
   <% @tab.each do |tab| %> <th scope="row">  </th>
   <tr>
     <td><%=tab.title %></td>
     <td><%=tab.price%></td>
   </tr>
   <%end%>
 </tbody>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %></br>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/items/index.html.erb
<!--########################-->
<!--####   container  ######-->
<!--########################-->
<section class="container">
  <div class="containerTitles">
    <h1>CHATS A VENDRE</h1>
  </div>

  <div class="component-systemTabs">
    <div class="tabs-container">
      <ul class="tabs"></ul>

      <div id="tab-1" data-tab-title="First" class="tab-content current">
        <div class="cards">

          <%@items.each do |item|%>
            <div class="card">
              <img src="<%=item.image_url%>">

              <div class="cardContent">
                <h2><%=item.title%><br></h2>
              <%=link_to "show", item_path(item.id), class:"btn btn-primary" %>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/items/show.html.erb
<img class = "showcat" src="<%= @item.image_url%>" alt="">
<div class="description">
  <b> Nom:</b><%= @item.title%> <br><br>
  <b>Prix: </b><%= @item.price%> <span>$</span> <br><br>
  <b> Détails:</b> <%= @item.description%><br><br><br><br>

  <%=link_to "ajouter au panier",carts_path ,class:"btn btn-info", type:"button",method: :POST%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ShopCats</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- KitUI -->
    <link rel="stylesheet" href="kitUI.css" type="text/css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bouttons loading -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header>
 <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">SHOPS CATS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Panier</a>
      </li>

  <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <a class="dropdown-item" href="<%=destroy_user_session_path%>" methode="delete">Se décconnecter</a>
        </div>
<% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'inscrire/Se connecter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%=new_user_registration_path%>">S'inscrire</a>
          <a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a>
        </div>
  <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <!-- Navbar -->

    </header>

<!-- insertion images chats-->
    <%= yield %>

<!--######################################-->
<!--######        Javascript        ######-->
<!--######################################-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>